# Credit Risk Resampling Techniques

In [1]:
#  Ingnore Warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Dependencies
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV and Perform Basic Data Cleaning

In [3]:
columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [4]:
# Load the data
file_path = Path('./Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

In [ ]:
# Quick Review df columns
df.info() 
#  115,675 rows. 86 columns. 

In [6]:
# View a few rows
df.head(3)

loan_amnt int_rate  installment home_ownership  annual_inc  \
0    20000.0   17.19%       499.10           RENT     47000.0   
1    21225.0   14.74%       502.05       MORTGAGE    225000.0   
2     5000.0   17.97%       180.69       MORTGAGE     62000.0   

  verification_status   issue_d loan_status pymnt_plan    dti  ...  \
0     Source Verified  Mar-2019      Issued          n  14.02  ...   
1        Not Verified  Mar-2019      Issued          n  16.80  ...   
2        Not Verified  Mar-2019      Issued          n  19.82  ...   

   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0            98.0              12.5                   0.0        0.0   
1           100.0              50.0                   1.0        0.0   
2            66.7              50.0                   0.0        0.0   

   tot_hi_cred_lim  total_bal_ex_mort total_bc_limit  \
0          75824.0            31546.0        33800.0   
1         747075.0           209426.0        53500.0   
2         255738.0            31615.0         9400.0   

   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                     21524.0              N                     N  
1                    128175.0              N                     N  
2                     39938.0              N                     N  

[3 rows x 86 columns]

In [7]:
# Drop the null columns where all values are null 
df = df.dropna(axis='columns', how='all')
df.head(3)
# Still 86 columns. Nothing dropped.

loan_amnt int_rate  installment home_ownership  annual_inc  \
0    20000.0   17.19%       499.10           RENT     47000.0   
1    21225.0   14.74%       502.05       MORTGAGE    225000.0   
2     5000.0   17.97%       180.69       MORTGAGE     62000.0   

  verification_status   issue_d loan_status pymnt_plan    dti  ...  \
0     Source Verified  Mar-2019      Issued          n  14.02  ...   
1        Not Verified  Mar-2019      Issued          n  16.80  ...   
2        Not Verified  Mar-2019      Issued          n  19.82  ...   

   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0            98.0              12.5                   0.0        0.0   
1           100.0              50.0                   1.0        0.0   
2            66.7              50.0                   0.0        0.0   

   tot_hi_cred_lim  total_bal_ex_mort total_bc_limit  \
0          75824.0            31546.0        33800.0   
1         747075.0           209426.0        53500.0   
2         255738.0            31615.0         9400.0   

   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                     21524.0              N                     N  
1                    128175.0              N                     N  
2                     39938.0              N                     N  

[3 rows x 86 columns]

In [ ]:
# Drop the null rows
df = df.dropna()
df.info()
# appx 30K rows dropped.  82,537 rows remain

In [ ]:
# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]
df.info()  # 68817 rows remain. 

In [10]:
# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100

In [11]:
# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)
x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

## Encode the text fields with LabelEncoder(), for use with modeling.

In [12]:
# Encode text fields
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['home_ownership'] = le.fit_transform(df['home_ownership']) 
df['verification_status'] = le.fit_transform(df['verification_status']) 
df['pymnt_plan'] = le.fit_transform(df['pymnt_plan']) 
df['hardship_flag'] = le.fit_transform(df['hardship_flag']) 
df['debt_settlement_flag'] = le.fit_transform(df['debt_settlement_flag']) 
df['debt_settlement_flag'] = le.fit_transform(df['debt_settlement_flag']) 
df['issue_d'] = le.fit_transform(df['issue_d']) 
df['initial_list_status'] = le.fit_transform(df['initial_list_status']) 
df['next_pymnt_d'] = le.fit_transform(df['next_pymnt_d']) 
df['application_type'] = le.fit_transform(df['application_type']) 
df['loan_status']= le.fit_transform(df['loan_status']) 
df.head(3)
## loan_status. low_risk = 1, High Risk = 0. 


loan_amnt  int_rate  installment  home_ownership  annual_inc  \
93     10500.0    0.1719       375.35               3     66000.0   
99     25000.0    0.2000       929.09               1    105000.0   
132    20000.0    0.2000       529.88               1     56000.0   

     verification_status  issue_d  loan_status  pymnt_plan    dti  ...  \
93                     1        2            1           0  27.24  ...   
99                     2        2            1           0  20.23  ...   
132                    2        2            1           0  24.26  ...   

     pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
93             85.7             100.0                   0.0        0.0   
99             91.2              50.0                   1.0        0.0   
132            66.7              50.0                   0.0        0.0   

     tot_hi_cred_lim  total_bal_ex_mort  total_bc_limit  \
93           65687.0            38199.0          2000.0   
99          271427.0            60641.0         41200.0   
132          60644.0            45684.0          7500.0   

     total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
93                      61987.0              0                     0  
99                      49197.0              0                     0  
132                     43144.0              0                     0  

[3 rows x 86 columns]

In [13]:
# Get the index in order
df.reset_index(inplace=True, drop=True)
df.head(3)

loan_amnt  int_rate  installment  home_ownership  annual_inc  \
0    10500.0    0.1719       375.35               3     66000.0   
1    25000.0    0.2000       929.09               1    105000.0   
2    20000.0    0.2000       529.88               1     56000.0   

   verification_status  issue_d  loan_status  pymnt_plan    dti  ...  \
0                    1        2            1           0  27.24  ...   
1                    2        2            1           0  20.23  ...   
2                    2        2            1           0  24.26  ...   

   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0            85.7             100.0                   0.0        0.0   
1            91.2              50.0                   1.0        0.0   
2            66.7              50.0                   0.0        0.0   

   tot_hi_cred_lim  total_bal_ex_mort  total_bc_limit  \
0          65687.0            38199.0          2000.0   
1         271427.0            60641.0         41200.0   
2          60644.0            45684.0          7500.0   

   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                     61987.0              0                     0  
1                     49197.0              0                     0  
2                     43144.0              0                     0  

[3 rows x 86 columns]

# Split the Data into Training and Testing

In [14]:
# Create our features
X = df.drop(columns=["loan_status"], axis=1)

In [15]:
# Create our target. Remember Low Risk is now 1 and High Risk is 0.
y = df["loan_status"]

In [ ]:
X.describe()
X.info()

In [ ]:
y.describe()

In [18]:
# Check the balance of our target values
y.value_counts()

1    68470
0      347
Name: loan_status, dtype: int64

In [19]:
# Create X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)

X_train.shape

(51612, 85)

## Scaling the data.  

In [20]:
# Scale the data
from sklearn.preprocessing import StandardScaler
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [21]:
# Resample the training data with the RandomOversampler from the imblearn library
# using random sampling to get a balanced training sets
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)

Counter(y_resampled)

Counter({1: 51352, 0: 51352})

In [22]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)

In [23]:
# Fit the Model
model.fit(X_resampled, y_resampled)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.7254573729609082

In [25]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[   59,    28],
       [ 3890, 13228]], dtype=int64)

In [26]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.01      0.68      0.77      0.03      0.72      0.52        87
          1       1.00      0.77      0.68      0.87      0.72      0.53     17118

avg / total       0.99      0.77      0.68      0.87      0.72      0.53     17205



### SMOTE Oversampling

In [27]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy="auto").fit_resample(
    X_train_scaled, y_train)

In [28]:
# Review the Counter
Counter(y_resampled)

Counter({1: 51352, 0: 51352})

In [29]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.7192136931884565

In [31]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   58,    29],
       [ 3907, 13211]], dtype=int64)

In [32]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.01      0.67      0.77      0.03      0.72      0.51        87
          1       1.00      0.77      0.67      0.87      0.72      0.52     17118

avg / total       0.99      0.77      0.67      0.87      0.72      0.52     17205



# Undersampling

In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [ ]:
# Resample the data using the ClusterCentroids resampler
# Tried to used the scaled data, but this ClusterCentroids would not complete in under an hour
# Using non scaled data ran in under 15 minutes. Interesting to explore, later.

from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)
Counter(y_resampled)

In [ ]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

In [35]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.49256580087103313

In [36]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   85,     2],
       [16979,   139]], dtype=int64)

In [37]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.00      0.98      0.01      0.01      0.09      0.01        87
          1       0.99      0.01      0.98      0.02      0.09      0.01     17118

avg / total       0.98      0.01      0.97      0.02      0.09      0.01     17205



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [41]:
# Resample the training data with SMOTEENN
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=1)
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)
Counter(y_resampled)
# ran in about 5 minutes: Counter({0: 51351, 1: 46389})
# now tyr scaled.

Counter({0: 51351, 1: 46389})

In [42]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [43]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.6160333345419824

In [44]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  60,   27],
       [7833, 9285]], dtype=int64)

In [45]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.01      0.69      0.54      0.02      0.61      0.38        87
          1       1.00      0.54      0.69      0.70      0.61      0.37     17118

avg / total       0.99      0.54      0.69      0.70      0.61      0.37     17205

